

#ifndef _DBGPRINTCUSTOM_H_
#define _DBGPRINTCUSTOM_H_

#define DBG_DEVICES(f)		\
	f(CLI)	\
	f(LOG)	\

#define DBG_OUT_ENCODED_HEADER				(DBG_OUT_STREAM_DEVICE_MASK_LOG)
#define DBG_OUT_DEVICES_USE_COLOR			(DBG_OUT_STREAM_DEVICE_MASK_CLI | DBG_OUT_STREAM_DEVICE_MASK_LOG)
#define DBG_OUT_DEFAULT_ENABLED_DEVICES		(DBG_OUT_STREAM_DEVICE_MASK_CLI)
#define DBG_MIN_MODULE_FOR_PREFIX			DBG_MODULE_DBGMENU

#define MODULES(f)	\
	f(MAIN,			ALL,	TRACE,	NONE,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_NONE)	\
	f(DBGMENU,		ALL,	TRACE,	NONE,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_NONE)	\
	f(BLE,			ALL,	TRACE,	INFO,	DBG_TERMINAL_COLOR_BLUE,	DBG_TERMINAL_COLOR_NONE)	\
	f(UART,			ALL,	INFO,	ERROR,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_NONE)	\
	f(ADC,			ALL,	INFO,	EWIT,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_NONE)	\
	f(CMD,			ALL,	INFO,	EWIT,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_NONE)	\
	f(I2C,			ALL,	NONE,	ERROR,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_NONE)	\
	f(PWM,			ALL,	INFO,	EWI,	DBG_TERMINAL_COLOR_MAGENTA,	DBG_TERMINAL_COLOR_NONE)	\
	f(APP,			ALL,	INFO,	EWIT,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_NONE)	\
	f(SERVICES,		ALL,	TRACE,	WARN,	DBG_TERMINAL_COLOR_GREEN,	DBG_TERMINAL_COLOR_NONE)	\
	f(PERSIST,		ALL,	TRACE,	WARN,	DBG_TERMINAL_COLOR_GREEN,	DBG_TERMINAL_COLOR_NONE)	\
	f(FIFO,			ALL,	INFO,	WARN,	DBG_TERMINAL_COLOR_GREEN,	DBG_TERMINAL_COLOR_NONE)	\
	f(VER,			ALL,	TRACE,	ALL,	DBG_TERMINAL_COLOR_GREEN,	DBG_TERMINAL_COLOR_NONE)	\
	f(KEEPER,		ALL,	TRACE,	ALL,	DBG_TERMINAL_COLOR_RED,		DBG_TERMINAL_COLOR_NONE)	\
	f(TIMER,		ALL,	TRACE,	ALL,	DBG_TERMINAL_COLOR_RED,		DBG_TERMINAL_COLOR_NONE)	\
	f(ASSERT,		ALL,	ALL,	ERROR,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_NONE)	\
	f(LAST,			NONE,	NONE,	NONE,	DBG_TERMINAL_COLOR_WHITE,	DBG_TERMINAL_COLOR_NONE)


#endif // _DBGPRINTCUSTOM_H_



